import { GoogleGenAI, GenerateContentResponse, Type } from "@google/genai";
import { ChirperUser } from '../types';

if (!process.env.API_KEY) {
  // In a real app, you might want to handle this more gracefully,
  // but for this context, throwing an error is fine.
  throw new Error("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
const modelName = 'gemini-2.5-flash';

export const getWriterSuggestion = async (prompt: string): Promise<string> => {
  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: modelName,
      contents: prompt,
      config: {
        temperature: 0.7,
        topP: 1,
        topK: 1,
      },
    });

    const text = response.text;
    if (typeof text !== 'string') {
        throw new Error("Invalid response format from Gemini API");
    }

    return text;
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    // You might want to re-throw a custom error or handle it as needed.
    throw new Error("Failed to fetch suggestion from Gemini API.");
  }
};

export const generateModelTexture = async (prompt: string): Promise<string> => {
    try {
        const fullPrompt = `A seamless, tileable texture pattern suitable for a 3D model, based on the following description: ${prompt}`;
        const response = await ai.models.generateImages({
            model: 'imagen-3.0-generate-002',
            prompt: fullPrompt,
            config: {
              numberOfImages: 1,
              outputMimeType: 'image/jpeg',
              aspectRatio: '1:1',
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0 && response.generatedImages[0].image?.imageBytes) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            const imageUrl = `data:image/jpeg;base64,${base64ImageBytes}`;
            return imageUrl;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error calling Gemini API for image generation:", error);
        throw new Error("Failed to generate model texture from Gemini API.");
    }
};

export const generateMacShopImage = async (prompt: string, width: number, height: number): Promise<string> => {
    try {
        const fullPrompt = `A retro, 8-bit or 16-bit pixel art style image. ${prompt}`;
        
        const supportedAspectRatios = {
            '1:1': 1,
            '4:3': 4/3,
            '3:4': 3/4,
            '16:9': 16/9,
            '9:16': 9/16,
        };
        const targetAspect = width / height;

        const bestRatio = Object.keys(supportedAspectRatios).reduce((prev, curr) => {
            const prevDiff = Math.abs(supportedAspectRatios[prev as keyof typeof supportedAspectRatios] - targetAspect);
            const currDiff = Math.abs(supportedAspectRatios[curr as keyof typeof supportedAspectRatios] - targetAspect);
            return currDiff < prevDiff ? curr : prev;
        }) as keyof typeof supportedAspectRatios;

        const response = await ai.models.generateImages({
            model: 'imagen-3.0-generate-002',
            prompt: fullPrompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/jpeg',
                aspectRatio: bestRatio,
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0 && response.generatedImages[0].image?.imageBytes) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            const imageUrl = `data:image/jpeg;base64,${base64ImageBytes}`;
            return imageUrl;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error calling Gemini API for image generation:", error);
        throw new Error("Failed to generate image from Gemini API.");
    }
};

export const createChirperPersona = async (bio: string): Promise<{ name: string, handle: string }> => {
    try {
        const prompt = `Based on the following user persona description, create a fictional user name and a Twitter-style handle (e.g., @example). Persona: "${bio}"`;
        const response = await ai.models.generateContent({
            model: modelName,
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        name: { type: Type.STRING },
                        handle: { type: Type.STRING },
                    },
                    required: ["name", "handle"]
                },
                temperature: 0.8,
            }
        });

        const jsonString = response.text.trim();
        const result = JSON.parse(jsonString);

        if (typeof result.name === 'string' && typeof result.handle === 'string') {
            return result;
        } else {
            throw new Error("Invalid persona format from API");
        }

    } catch (error) {
        console.error("Error creating Chirper persona:", error);
        throw new Error("Failed to create AI persona.");
    }
};

export const generateChirperFeed = async (users: ChirperUser[]): Promise<{ chirps: { userId: string, content: string }[] }> => {
    try {
        const userDescriptions = users.map(u => `- User ID ${u.id} (handle: ${u.handle}, name: ${u.name}): ${u.bio}`).join('\n');
        const prompt = `You are a social media post generator. Based on the following list of user personas, generate a short, Twitter-like post (under 280 characters) for each user.

Users:
${userDescriptions}

Generate one post per user ID. Make sure the content of the post fits the user's persona.`;
        
        const response = await ai.models.generateContent({
            model: modelName,
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        chirps: {
                            type: Type.ARRAY,
                            items: {
                                type: Type.OBJECT,
                                properties: {
                                    userId: { type: Type.STRING },
                                    content: { type: Type.STRING }
                                },
                                required: ["userId", "content"]
                            }
                        }
                    },
                    required: ["chirps"]
                },
                temperature: 0.9,
            }
        });

        const jsonString = response.text.trim();
        const result = JSON.parse(jsonString);

        if (result.chirps && Array.isArray(result.chirps)) {
            return result;
        } else {
             throw new Error("Invalid feed format from API");
        }
    } catch (error) {
        console.error("Error generating Chirper feed:", error);
        throw new Error("Failed to generate AI feed.");
    }
};